import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <div className={styles.background} /> {/* Add this line */}
      <Head>
        <title>XAO Cult</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>

        <div className={styles.linkDiv}>
          <Link href="/wallets">
            <button className={styles.bigButton}>
              <Image
                src="/MetaMask-icon-fox.svg"
                alt="Wallet Icon"
                width={20}
                height={20}
                className={styles.buttonIcon}
              />
              Sign in with Wallet
            </button>
          </Link> 
        </div>
        <button className={styles.bigButton}>
          <span role="img" aria-label="passkey" className={styles.passkeyIcon}>
            🔑
          </span>
          Sign in with Passkey
        </button>
        <div className={styles.gradientLine} />
        <Image
            alt="XAO Monster"
            src="/xao-monster.png"
            width={250}
            height={250}
            style={{ width: '25%', height: 'auto', maxWidth: '100%' }}
          />     
      </main>
    </div>
  );
};

export default Home;
