import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image'
import styles from '../styles/Home.module.css';
import Link from 'next/link';
import { WalletButton } from '@rainbow-me/rainbowkit';

const Wallets: NextPage = () => {
  return (
    <div className={styles.container}>
      <div className={styles.background} /> 
      <Head>
        <title>XAO Cult</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

    <main className={styles.main}>
      <WalletButton wallet="rainbow" className={styles.bigButton} />
      <WalletButton wallet="metamask" className={styles.bigButton} />
      <WalletButton wallet="coinbase" className={styles.bigButton} />
      <div className={styles.gradientLine} />
      <div className={styles.linkDiv}>
        <Link href="/">
        <Image
          alt="XAO Monster"
          src="/xao-monster.png"
          width={250}
          height={250}
          style={{ width: '25%', height: 'auto', maxWidth: '100%' }}
        />
        </Link>
      </div>
    </main>
    </div>
  );
};

export default Wallets;
